contract_name,bugs_name,timestamp,logs
mishandled.wasm,Reentrancy,2024-01-22_19-28-26,"{""success"": false, ""error"": ""Traceback (most recent call last):\n  File \""/usr/local/lib/python3.8/dist-packages/mythril-0.23.15-py3.8.egg/mythril/interfaces/cli.py\"", line 943, in parse_args_and_execute\n    address = load_code(disassembler, args)\n  File \""/usr/local/lib/python3.8/dist-packages/mythril-0.23.15-py3.8.egg/mythril/interfaces/cli.py\"", line 698, in load_code\n    address, _ = disassembler.load_from_solidity(\n  File \""/usr/local/lib/python3.8/dist-packages/mythril-0.23.15-py3.8.egg/mythril/mythril/mythril_disassembler.py\"", line 172, in load_from_solidity\n    solc_binary = self.solc_binary or util.extract_binary(file)\n  File \""/usr/local/lib/python3.8/dist-packages/mythril-0.23.15-py3.8.egg/mythril/ethereum/util.py\"", line 175, in extract_binary\n    version = extract_version(f.read())\n  File \""/usr/lib/python3.8/codecs.py\"", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0x8c in position 9: invalid start byte\n"", ""issues"": []}
"
